server:
  port: 81

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      #defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: order80

spring:
  application:
    name: cloud-order-server