server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url:  http://localhost:9411
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.100:1111


management:
  endpoints:
    web:
      exposure:
        include: '*'