server:
  port: 2003

spring:
  application:
    name: seata-account-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    seata:
      enabled: true
      tx-service-group: my_tx_group
      service:
        vgroup-mapping:
          my_tx_group: default
        registry:
          type: nacos
          nacos:
            application: seata-server
            server-addr: localhost:8848
            namespace:
              group: DEFAULT_GROUP
        config:
          type: nacos
          nacos:
            server-addr: localhost:8848
            namespace: seata
            group: DEFAULT_GROUP
            data-id: seataServer.properties

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.lynne.springcloud.alibaba.dao
