server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://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@github.com/lyfengluo/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
    fetch-registry: true
    register-with-eureka: true


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'