server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    seata:
      enable: true
      tx-service-group: my_tx_group
      service:
        vgroup-mapping:
          my_tx_group: default
        registry:
          type: nacos
          nacos:
            application: seata-server
            server-addr: localhost:8848
            namespace: seata
            group: DEFAULT_GROUP
        config:
          type: nacos #配置中心
          nacos:
            server-addr: localhost:8848
            #namespace: seata
            group: DEFAULT_GROUP
            data-id: seataServer.properties
logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lynne.springcloud.alibaba.domain
