server:
  port: 85


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
    fetch-registry: true
    register-with-eureka: true
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
spring:
  application:
    name: cloud-consumer-hystrix-order

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
